version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: brain-tasks-app
    IMAGE_TAG: latest
    CLUSTER_NAME: brain-tasks-cluster

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region ap-south-1 |
        docker login --username AWS --password-stdin 620916944925.dkr.ecr.ap-south-1.amazonaws.com
      - echo Updating kubeconfig for EKS cluster
      - aws eks update-kubeconfig --region ap-south-1 --name brain-tasks-cluster

  build:
    commands:
      - echo Build started
      - docker build -t brain-tasks-app:latest .
      - docker tag brain-tasks-app:latest 620916944925.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push 620916944925.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
      - echo Deploying application to EKS
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
